name: Node.js CI

on:
  pull_request:
    branches: 
      - "development"

jobs:
  type-check-lint-test-build:
    name: type-check-lint-test-build
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: 'npm'
    - name: Install Nx
      run: npm install nx
    - name: Install Dependencies
      run: npm install
    - name: Check Types
      run: npm run typecheck
    - name: Run Linting Rules
      run: npm run lint
    - name: Create .env file
      run: |
        echo "${{ secrets.TEST_ENV }}" > ./apps/server/.env.test
    - name: Run Migration
      run: npm run migrate
    - name: Run Tests
      run: npm run test
    - name: Build
      run: npm run build
