# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - "9-basic-ci-pipeline-with-github-actions"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [typecheck, lint, test]
    strategy:
      matrix:
        node-version: 18.x

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 18.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install nx
    - run: npm install
    - run: npm typecheck
  lint:
    name: lint
    needs: typecheck
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 18.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [typecheck, lint]
    
    strategy:
      matrix:
        node-version: 18.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm test