name: Node.js CI

on:
  pull_request:
    branches: 
      - "development"

jobs:
  type-check-lint-test-build:
    name: type-check-lint-test-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: 'npm'
    - name: Install Dependencies
      run: npm install nx
      run: npm install
    - name: Check Types
      run: npm run typecheck
    - name: Run Linting Rules
      run: npm run lint
    - name: Run Tests
      run: npm run test
    - name: Build
      run: npm run build
